project:
  type: website

website:
  title: "SingleCell RNA-seq Workshop"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: sc_scripts.qmd
        text: General Scripts
      - href: sc_integrating.qmd
        text: Integration Scripts
      - href: sc_metacell.qmd
        text: Metacell Scripts

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    
execute:
  freeze: auto